FROM php:8.4-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
  nginx \
  git \
  unzip \
  libpng-dev \
  libonig-dev \
  libxml2-dev \
  libzip-dev \
  zip \
  curl \
  && docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath gd

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Copy app
COPY app/ /var/www

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# Copy compiled frontend assets (VERY IMPORTANT)
COPY app/public/build /var/www/public/build

# Copy nginx config
COPY docker/nginx.conf /etc/nginx/nginx.conf

# Permissions
RUN chown -R www-data:www-data /var/www \
  && chmod -R 755 /var/www/storage

EXPOSE 80

CMD ["sh", "-c", "php-fpm & nginx -g 'daemon off;'"]
